# nixpacks.toml - Configuración para el builder de Railway
[phases.setup]
nixPkgs = ['nodejs_18', 'postgresql']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start:prod'