# nixpacks.toml - Configuración para el builder de Railway
[phases.setup]
nixPkgs = ['nodejs_18', 'postgresql', 'python3']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build && mkdir -p logs/pm2 uploads/excel']

[start]
cmd = 'npm run start:prod'

[phases.setup.aptPkgs]
packages = ["build-essential", "python3-dev"]