# railway.toml - Configuración para Railway
[build]
builder = "nixpacks"
buildCommand = "npm install"
watchPatterns = ["server/**", "package.json", "src/**", "nixpacks.toml", "Procfile"]

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# Health check configurado para usar la ruta /health
healthcheckPath = "/api/health"
healthcheckTimeout = 10
healthcheckTimeout = 10

[service]
# Auto-scaling options
autoscaling.enabled = true
autoscaling.min = 1
autoscaling.max = 3

# Health check
healthcheck.enabled = true
healthcheck.path = "/api/health"
healthcheck.interval = "30s"
healthcheck.timeout = "5s"
healthcheck.interval = "30s"
healthcheck.timeout = "5s"

[env]
PORT = "3002"
NODE_ENV = "production"